export const GET_USERS = "GET_USERS"
export const DATA_USERS_CHANGE = "DATA_USERS_CHANGE"
export const SEARCH_USERS = "SEARCH_USERS"
export const DATA_SEARCH_USERS_CHANGE = "DATA_SEARCH_USERS_CHANGE"

export const SET_FAVORITE = "SET_FAVORITE"
export const REMOVE_FAVORITE = "REMOVE_FAVORITE"




